### ISSUE TITLE
Plugin crashes when importing data "cf_service"

### ISSUE THREAD

**Issue by pedrodparkes** [cloudfoundry-community/terraform-provider-cf#139]
App crashes on "cf_service" data-source if "space" name is specified

```
data "cf_service" "myService" {
    name = "MyService"  
    space = "MyspaceName"  
}
```

```
tf plan                                                                                                                               14:43:33
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.cf_stack.Linux: Refreshing state...
data.cf_info.info: Refreshing state...
data.cf_service.Mongo: Refreshing state...
data.cf_service.Autoscaler: Refreshing state...
data.cf_service.MongoLoadTest: Refreshing state...

Error: Error refreshing state: 3 error(s) occurred:

* data.cf_service.MongoLoadTest: 1 error(s) occurred:

* data.cf_service.MongoLoadTest: data.cf_service.MongoLoadTest: unexpected EOF
* data.cf_service.Mongo: 1 error(s) occurred:

* data.cf_service.Mongo: data.cf_service.Mongo: unexpected EOF
* data.cf_service.Autoscaler: 1 error(s) occurred:

* data.cf_service.Autoscaler: data.cf_service.Autoscaler: unexpected EOF


panic: runtime error: index out of range
2018-09-17T14:43:36.115+0200 [DEBUG] plugin.terraform-provider-cf: 
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: goroutine 91 [running]:
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi.(*ServiceManager).FindSpaceService(0xc420306540, 0xc42049bde0, 0x15, 0xc42001a630, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: 	/home/travis/gopath/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi/service_manager.go:706 +0x364
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: github.com/terraform-providers/terraform-provider-cf/cloudfoundry.dataSourceServiceRead(0xc420268070, 0x120b900, 0xc42009c2c0, 0xc420268070, 0x0)
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: 	/home/travis/gopath/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/data_source_cf_service.go:58 +0x354
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc420200620, 0xc4203b4320, 0x120b900, 0xc42009c2c0, 0xc42023ce70, 0xc420342701, 0x80000000018)
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: 	/home/travis/gopath/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:292 +0x8b
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc4202015e0, 0xc42026a190, 0xc4203b4320, 0x7fb73c71c458, 0x0, 0x0)
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: 	/home/travis/gopath/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:426 +0x9a
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0xc4202eeb20, 0xc42033a690, 0xc42033a6c0, 0x0, 0x0)
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: 	/home/travis/gopath/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:604 +0x4e
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: reflect.Value.call(0xc4205028a0, 0xc42000e9e0, 0x13, 0x125843c, 0x4, 0xc420040f20, 0x3, 0x3, 0xc4203a81d8, 0xc420288058, ...)
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: 	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/reflect/value.go:434 +0x905
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: reflect.Value.Call(0xc4205028a0, 0xc42000e9e0, 0x13, 0xc420395720, 0x3, 0x3, 0xc420395760, 0x64ea05, 0xc420288000)
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: 	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/reflect/value.go:302 +0xa4
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: net/rpc.(*service).call(0xc4203643c0, 0xc42026a0f0, 0xc420476360, 0xc42036ab80, 0xc4204ec2c0, 0x100a0a0, 0xc42033a690, 0x16, 0x100a0e0, 0xc42033a6c0, ...)
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: 	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/rpc/server.go:381 +0x142
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: created by net/rpc.(*Server).ServeCodec
2018-09-17T14:43:36.116+0200 [DEBUG] plugin.terraform-provider-cf: 	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/rpc/server.go:475 +0x36b
2018/09/17 14:43:36 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.cf_service.MongoLoadTest: unexpected EOF
2018/09/17 14:43:36 [ERROR] root: eval: *terraform.EvalSequence, err: data.cf_service.MongoLoadTest: unexpected EOF
2018/09/17 14:43:36 [TRACE] [walkRefresh] Exiting eval tree: data.cf_service.MongoLoadTest
2018/09/17 14:43:36 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.cf_service.Mongo: unexpected EOF
2018/09/17 14:43:36 [ERROR] root: eval: *terraform.EvalSequence, err: data.cf_service.Mongo: unexpected EOF
2018/09/17 14:43:36 [TRACE] [walkRefresh] Exiting eval tree: data.cf_service.Mongo
2018/09/17 14:43:36 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.cf_service.Autoscaler: unexpected EOF
2018/09/17 14:43:36 [ERROR] root: eval: *terraform.EvalSequence, err: data.cf_service.Autoscaler: unexpected EOF
2018/09/17 14:43:36 [TRACE] [walkRefresh] Exiting eval tree: data.cf_service.Autoscaler
2018-09-17T14:43:36.118+0200 [DEBUG] plugin: plugin process exited: path=/home/vsamotaev/.terraform.d/providers/terraform-provider-cf
2018/09/17 14:43:36 [TRACE] dag/walk: upstream errored, not walking "provider.cf (close)"
2018/09/17 14:43:36 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-09-17T14:43:36.118+0200 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by janosbinder** [comment]
Hi @pedrodparkes ,

thank you for report. Can you please checkout the `dev` branch and try to reproduce the error with it? We are on the way to release 1.0 and that branch contains a lot of fixes. Please rename all `cf_` resources/data to `cloudfoundry_` and get back to us, whether the error still occurs.

**Comment by gberche-orange** [comment]
thanks @pedrodparkes for reporting this problem. I'm closing for now until you/we can reproduce on the latest dev branch. We should provide shortly new binaires in upcoming release, see #113 Feel free to reopen then

**Comment by pedrodparkes** [comment]
problem appears on DEV branch!
pls reopen

**Comment by ArthurHlt** [comment]
Data source has been rewritten and api call has been totally reworked  on #203 . Index out of range can't occurred here. I'm closing it, let us know if you still have issue with #203 . Take note that it will requires you terraform 0.12 to run this version
