### ISSUE TITLE
Port error when updating docker image in app

### ISSUE THREAD

**Issue by lixilin2301** [cloudfoundry-community/terraform-provider-cf#179]
When updating the docker image, I got following crash when TF tried to read app. I think this is related to https://github.com/mevansam/terraform-provider-cf/blob/dev/cloudfoundry/resource_cf_app.go#L652, which got a nil pointer.

```
Error: Error refreshing state: 1 error(s) occurred:

* cloudfoundry_app.hello-push: 1 error(s) occurred:

* cloudfoundry_app.hello-push: cloudfoundry_app.hello-push: unexpected EOF


panic: interface conversion: interface {} is nil, not int
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: 
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: goroutine 481 [running]:
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry.resourceAppRead(0xc4203410a0, 0x1d608e0, 0xc420278f00, 0xc4203410a0, 0x0)
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: 	/Users/d071651/gocode/src/github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/resource_cf_app.go:652 +0xffc
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cloudfoundry/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4203eeb60, 0xc4205bfea0, 0x1d608e0, 0xc420278f00, 0xc4200d79e8, 0x10bbd01, 0x1b5a500)
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: 	/Users/d071651/gocode/src/github.com/terraform-providers/terraform-provider-cloudfoundry/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x167
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cloudfoundry/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4203eecb0, 0xc4205bfe50, 0xc4205bfea0, 0xc4202aeb80, 0x1083143, 0xc4201dcf00)
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: 	/Users/d071651/gocode/src/github.com/terraform-providers/terraform-provider-cloudfoundry/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cloudfoundry/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc42036cf20, 0xc4201c17a0, 0xc4201c18e0, 0x0, 0x0)
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: 	/Users/d071651/gocode/src/github.com/terraform-providers/terraform-provider-cloudfoundry/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: reflect.Value.call(0xc420174de0, 0xc4200de8c8, 0x13, 0x1dabc09, 0x4, 0xc4202aef18, 0x3, 0x3, 0xc4201cc000, 0xc420428388, ...)
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: 	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:447 +0x969
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: reflect.Value.Call(0xc420174de0, 0xc4200de8c8, 0x13, 0xc42069cf18, 0x3, 0x3, 0x1, 0x124a4ce, 0x1)
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: 	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:308 +0xa4
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: net/rpc.(*service).call(0xc420045400, 0xc4200e1f40, 0xc420348f98, 0xc420349000, 0xc4201dcb00, 0xc42036c9c0, 0x1b5a4c0, 0xc4201c17a0, 0x16, 0x1b5a500, ...)
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: 	/usr/local/Cellar/go/1.10.3/libexec/src/net/rpc/server.go:384 +0x14e
2018-12-14T09:56:53.256+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: created by net/rpc.(*Server).ServeCodec
2018-12-14T09:56:53.257+0100 [DEBUG] plugin.terraform-provider-cloudfoundry: 	/usr/local/Cellar/go/1.10.3/libexec/src/net/rpc/server.go:480 +0x43a
2018/12/14 09:56:53 [ERROR] root: eval: *terraform.EvalRefresh, err: cloudfoundry_app.hello-push: unexpected EOF
2018/12/14 09:56:53 [ERROR] root: eval: *terraform.EvalSequence, err: cloudfoundry_app.hello-push: unexpected EOF
2018/12/14 09:56:53 [TRACE] [walkRefresh] Exiting eval tree: cloudfoundry_app.hello-push
2018/12/14 09:56:53 [TRACE] dag/walk: upstream errored, not walking "provider.cloudfoundry (close)"
2018-12-14T09:56:53.260+0100 [DEBUG] plugin: plugin process exited: path=/Users/d071651/.terraform.d/plugins/darwin_amd64/terraform-provider-cloudfoundry
2018/12/14 09:56:53 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-12-14T09:56:53.260+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

If I comment this line out, I got following error instead. I cannot reproduce following error in acceptance tests, for which I assume this is a platform-related problem. Not very sure, if anyone has an idea, please let me know. 
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ cloudfoundry_app.hello-push
      docker_image: "somerepo/diego-docker-app:1.0" => "somerepo/diego-docker-app:1.1"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudfoundry_app.hello-push: Modifying... (ID: 7bc755dd-2d2a-47fa-b4b0-6afae1e04039)
  docker_image: "somerepo/diego-docker-app:1.0" => "somerepo/diego-docker-app:1.1"

Error: Error applying plan:

1 error(s) occurred:

* cloudfoundry_app.hello-push: 1 error(s) occurred:

* cloudfoundry_app.hello-push: Server error, status code: 400, error code: 100001, message: The app is invalid: ports App ports ports may not be removed while routes are mapped to them. To change the app port a route is mapped to add the new ports to your app, change the app port the route is mapped to, then remove unused app ports.
```

**Comment by lixilin2301** [comment]
Following I attached the setup I used for tests:
```
data "cloudfoundry_stack" "my_stack" {
  name = "${var.cloudfoundry_stack}"
}

data "cloudfoundry_org" "org_mysuperorg" {
  name = "${var.cloudfoundry_org_name}"
}

data "cloudfoundry_space" "space_mysuperspace" {
  name = "${var.cloudfoundry_space_name}"
  org  = "${data.cloudfoundry_org.org_mysuperorg.id}"
}

data "cloudfoundry_domain" "domain_mydomain" {
  name = "${var.cloudfoundry_ending_domain_name}"
}

provider "cloudfoundry" {
  api_url  = "${var.cloudfoundry_api_url}"
  user     = "${var.user}"
  password = "${var.password}"
}

resource "cloudfoundry_app" "hello-push" {
	name = "hello-push"
	space = "${data.cloudfoundry_space.space_mysuperspace.id}"
	
	memory = "512"
	disk_quota = "512"
	timeout = 1800
	
	docker_image = "somerepo/diego-docker-app:1.1"

	routes {
		route = "${cloudfoundry_route.hello-push.id}"
	}
}

resource "cloudfoundry_route" "hello-push" {
	domain = "${data.cloudfoundry_domain.domain_mydomain.id}"
	space = "${data.cloudfoundry_space.space_mysuperspace.id}"
	hostname = "hello-push"
}
```

**Comment by viperx77** [comment]
I'm having the exact same problem.  Any progress?

**Comment by janosbinder** [comment]
Actually we have the fix on our fork (https://github.com/chrismathias/terraform-provider-cf/commits/dev-bluegreen), but we have not had the time to backport it. @lixilin2301 should we discuss internally how we submit our fixes against the upstream repo?

**Comment by viperx77** [comment]
I'm curious why you would fork vs contributing the fixes and enhancements to this project?

**Comment by janosbinder** [comment]
We have a prototype blue-green implementation, which is not merged here. As it is somewhat complicated and not mature, we found some bugs, which we have fixed there. Some of them also affects this codebase.

However we regularly submit PR against the upstream repo. You can see it in the changelog.

**Comment by viperx77** [comment]
Cool. I look forward to these bug fixes.

**Comment by viperx77** [comment]
@janosbinder, I tried out the dev-bluegreen branch and it seemed to work fine:

```
    blue_green {
        enable = true
        shutdown_wait = 1
    }
```
I saw it create the {app}-venerable and switch the route. This will be a great addition to the provider.

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.

Note that blue-green has been implemented but the approcah is different: https://github.com/cloudfoundry-community/terraform-provider-cf/wiki/resource_app#application-deployment-strategy-blue-green-deploy
